source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'pg', '~> 0.17.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'turbolinks', '= 2.5.3'
gem 'turboboost'
gem 'nprogress-rails'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'cancancan', '~> 1.10'
gem 'carrierwave'
gem 'rails-i18n'
gem 'translit'
gem 'will_paginate'
gem 'curb'
gem 'truncate_html'
gem 'mini_magick', '~> 4.2.10'
gem 'gretel'
gem 'rails-api'
gem 'vkontakte_api', '~> 1.4'
gem 'koala', '~> 2.0'
gem 'apipie-rails'
gem 'rpush'
gem 'magnific-popup-rails', '~> 1.1.0'
gem 'gaffe'
gem 'dotenv-rails'

group :development, :test do
	gem 'pry-rails'
	gem 'meta_request'
	gem 'better_errors'
	gem 'binding_of_caller'
	gem 'byebug'
	gem 'mailcatcher'
	gem 'quiet_assets'
	gem 'mina'
end